"""corrected a table

Revision ID: d9eec5d24fea
Revises: 
Create Date: 2024-07-21 15:29:59.118617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9eec5d24fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('times', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('times')
        batch_op.drop_column('days')

    # ### end Alembic commands ###
